version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - 5000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/log:/var/log/nginx/
        links:
            - api
        environment:
            TZ: Asia/Tokyo

    web:
        build: ./web
        ports:
            - 8080:80
        environment:
            TZ: Asia/Tokyo

    api:
        build: ./api
        ports:
            - 3031:3031
        volumes:
            - ./api:/opt/api
        links:
            - db
        tty: true
        environment:
            FLASK_APP: run.py
            TZ: Asia/Tokyo
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASS}

    db:
        image: mysql:8.0
        ports:
          - 13306:3306
        volumes:
            - db-store:/var/lib/mysql
            - ./db/logs:/var/log/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/sqls:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            TZ: Asia/Tokyo

volumes:
    db-store:
